//! Native QC against synthetic fixtures generated by the pinned FFmpeg, and
//! the render worker's QC failure paths (plan step 5).

use std::collections::BTreeSet;

use serde_json::json;

use super::*;
use crate::video::{
    qc::{
        analyze_output, subtitle_findings, EditorialEvaluation, QcAnalysisConfig, QcFinding,
        QcFindingKind, QcRange, QcSeverity, QcSource, QcStatus, QcThresholds, RenderQcContext,
    },
    render::RenderWorkerHooks,
    render_manifest::manifest_path_for,
    types::{RenderCaptionInput, RenderCaptionStyle},
};

const STATE: &str = "5555555555555555555555555555555555555555555555555555555555555555";

fn pinned_binary() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("media-toolchain/bin/x86_64-pc-windows-msvc/ffmpeg.exe")
}

pub(super) fn bundled_programs(root: &Path) -> MediaPrograms {
    let destination = root.join("media-tools");
    fs::create_dir_all(&destination).unwrap();
    let staged =
        Path::new(env!("CARGO_MANIFEST_DIR")).join("media-toolchain/bin/x86_64-pc-windows-msvc");
    for name in ["ffmpeg.exe", "ffprobe.exe"] {
        fs::copy(staged.join(name), destination.join(name))
            .expect("pinned resources missing: run media:bootstrap:windows");
    }
    let toolchain = super::super::toolchain::MediaToolchain::resolve_from_resource_root(root);
    MediaPrograms::bundled(super::super::toolchain::MediaToolchainState::from_ready(
        toolchain,
    ))
}

/// Builds a 4 s 320×180@30 H.264/AAC fixture from lavfi graphs.
pub(super) fn make_fixture(directory: &Path, name: &str, video: &str, audio: &str) -> PathBuf {
    let output = directory.join(format!("{name}.mp4"));
    let status = Command::new(pinned_binary())
        .args(["-hide_banner", "-nostdin", "-v", "error", "-y"])
        .args(["-f", "lavfi", "-i", video, "-f", "lavfi", "-i", audio])
        .args(["-t", "4", "-map", "0:v", "-map", "1:a"])
        .args([
            "-c:v",
            "libx264",
            "-preset",
            "ultrafast",
            "-pix_fmt",
            "yuv420p",
        ])
        .args(["-c:a", "aac", "-b:a", "192k", "-ar", "48000", "-ac", "2"])
        .arg(&output)
        .status()
        .expect("pinned FFmpeg must run");
    assert!(status.success(), "fixture {name} must be generated");
    output
}

pub(super) const CLEAN_VIDEO: &str = "testsrc2=s=320x180:r=30:d=4";
pub(super) const CLEAN_AUDIO: &str = "sine=f=440:sample_rate=48000:d=4";

fn config(target: Option<f64>) -> QcAnalysisConfig {
    QcAnalysisConfig {
        duration_us: 4_000_000,
        has_audio: true,
        video_hidden: false,
        loudness_target_lufs: target,
        thresholds: QcThresholds::default(),
        timeout: Duration::from_secs(120),
    }
}

async fn kinds_for(
    programs: &MediaPrograms,
    path: &Path,
    target: Option<f64>,
) -> Vec<(QcFindingKind, QcSeverity)> {
    let findings = analyze_output(
        programs,
        ProcessCancellation::new(),
        path,
        &config(target),
        &[],
        (320, 180),
        STATE,
    )
    .await
    .expect("QC pass must succeed on a valid fixture");
    findings
        .iter()
        .map(|finding| (finding.kind, finding.severity))
        .collect()
}

#[tokio::test]
async fn qc_detectors_report_exactly_the_expected_finding_per_fixture() {
    let workspace = tempdir().unwrap();
    let programs = bundled_programs(workspace.path());
    let directory = workspace.path();
    type Case = (
        &'static str,
        PathBuf,
        Option<f64>,
        Vec<(QcFindingKind, QcSeverity)>,
    );
    let cases: Vec<Case> = vec![
        (
            "clean",
            make_fixture(directory, "clean", CLEAN_VIDEO, CLEAN_AUDIO),
            None,
            vec![],
        ),
        (
            "black",
            make_fixture(
                directory,
                "black",
                "color=black:s=320x180:r=30:d=2[b];testsrc2=s=320x180:r=30:d=2[t];[b][t]concat=n=2:v=1:a=0",
                CLEAN_AUDIO,
            ),
            None,
            vec![(QcFindingKind::BlackFrames, QcSeverity::Blocker)],
        ),
        (
            "freeze",
            make_fixture(
                directory,
                "freeze",
                "testsrc2=s=320x180:r=30:d=1,tpad=stop_mode=clone:stop_duration=3",
                CLEAN_AUDIO,
            ),
            None,
            vec![(QcFindingKind::FreezeFrames, QcSeverity::Blocker)],
        ),
        (
            "silence",
            make_fixture(
                directory,
                "silence",
                CLEAN_VIDEO,
                "sine=f=440:sample_rate=48000:d=1,apad=whole_dur=4",
            ),
            None,
            vec![(QcFindingKind::Silence, QcSeverity::Warning)],
        ),
        (
            "clipped",
            make_fixture(
                directory,
                "clipped",
                CLEAN_VIDEO,
                "sine=f=440:sample_rate=48000:d=4,volume=40",
            ),
            None,
            vec![(QcFindingKind::AudioClipping, QcSeverity::Blocker)],
        ),
        (
            "loudness",
            make_fixture(directory, "loudness", CLEAN_VIDEO, CLEAN_AUDIO),
            Some(-40.0),
            vec![(QcFindingKind::LoudnessOffTarget, QcSeverity::Blocker)],
        ),
    ];
    for (name, path, target, expected) in cases {
        assert_eq!(
            kinds_for(&programs, &path, target).await,
            expected,
            "fixture {name}"
        );
    }
}

fn caption(
    text: &str,
    start: u64,
    end: u64,
    style: Option<RenderCaptionStyle>,
) -> RenderCaptionInput {
    serde_json::from_value(json!({
        "trackId": "66666666-6666-4666-8666-666666666601",
        "captionId": "66666666-6666-4666-8666-666666666602",
        "startMicroseconds": start,
        "endMicroseconds": end,
        "text": text,
    }))
    .map(|caption: RenderCaptionInput| RenderCaptionInput { style, ..caption })
    .expect("caption fixture must deserialize")
}

fn style(font_size_px: u64) -> RenderCaptionStyle {
    RenderCaptionStyle {
        font: "arial".to_owned(),
        font_size_px,
        line_spacing_px: 4,
        color_rgba: "#ffffffff".to_owned(),
        horizontal: "center".to_owned(),
        vertical: "bottom".to_owned(),
        anchor_x_permille: 500,
        anchor_y_permille: 900,
        safe_top_permille: 50,
        safe_right_permille: 50,
        safe_bottom_permille: 50,
        safe_left_permille: 50,
    }
}

#[test]
fn subtitle_bounds_flag_overflow_and_out_of_time_cues_only() {
    let fits = caption("Short line", 0, 1_000_000, Some(style(24)));
    let wide = caption(
        "This caption line is far too long for a vertical frame",
        0,
        1_000_000,
        Some(style(64)),
    );
    let late = caption("Late", 3_500_000, 5_000_000, None);
    assert!(subtitle_findings(&[fits], 4_000_000, 1920, 1080, STATE).is_empty());
    let overflow = subtitle_findings(&[wide], 4_000_000, 1080, 1920, STATE);
    assert_eq!(overflow.len(), 1);
    assert_eq!(overflow[0].kind, QcFindingKind::SubtitleOutOfBounds);
    assert_eq!(overflow[0].severity, QcSeverity::Blocker);
    let timed = subtitle_findings(&[late], 4_000_000, 1920, 1080, STATE);
    assert_eq!(timed.len(), 1);
    assert_eq!(timed[0].range.end_us, 4_000_000);
}

fn empty_context(validated: &super::super::render::ValidatedRenderPlan) -> RenderQcContext {
    RenderQcContext {
        revision_state_hash: STATE.to_owned(),
        editorial: EditorialEvaluation {
            evaluator_version: "editorial-v1".to_owned(),
            revision_id: validated.plan.revision_id().as_str().to_owned(),
            revision_state_hash: STATE.to_owned(),
            findings: Vec::new(),
        },
        delivery: None,
    }
}

struct WorkerRun {
    _workspace: tempfile::TempDir,
    output: PathBuf,
    partial: PathBuf,
    events: Vec<VideoRenderEvent>,
}

/// Runs the real worker on a fixture with QC enabled and the given hooks.
async fn run_qc_worker(source_video: &str, hooks: RenderWorkerHooks, plan_id: &str) -> WorkerRun {
    run_qc_worker_with(source_video, hooks, plan_id, |_| Vec::new()).await
}

async fn run_qc_worker_with(
    source_video: &str,
    hooks: RenderWorkerHooks,
    plan_id: &str,
    editorial_findings: impl Fn(&str) -> Vec<QcFinding>,
) -> WorkerRun {
    let workspace = tempdir().unwrap();
    let programs = bundled_programs(workspace.path());
    let source = make_fixture(workspace.path(), "source", source_video, CLEAN_AUDIO);
    let (output, partial, events) = render_once(
        workspace.path(),
        &programs,
        &source,
        plan_id,
        false,
        hooks,
        &editorial_findings,
    )
    .await;
    WorkerRun {
        _workspace: workspace,
        output,
        partial,
        events,
    }
}

async fn render_once(
    root: &Path,
    programs: &MediaPrograms,
    source: &Path,
    plan_id: &str,
    overwrite: bool,
    hooks: RenderWorkerHooks,
    editorial_findings: &dyn Fn(&str) -> Vec<QcFinding>,
) -> (PathBuf, PathBuf, Vec<VideoRenderEvent>) {
    let mut validated =
        validated_system_render_fixture(root, source, true, plan_id, CANONICAL_RENDER_PROFILE);
    let mut context = empty_context(&validated);
    context.editorial.findings = editorial_findings(STATE);
    validated.qc = Some(context);
    let output = validated.output_path.clone();
    let partial = partial_render_path(&validated).unwrap();
    let (mut request, captured) = registered_render_worker(
        validated,
        overwrite,
        root.join("app-cache"),
        programs.clone(),
    );
    request.hooks = hooks;
    run_render_worker(request).await;
    (output, partial, captured_render_events(&captured))
}

fn terminal(run: &WorkerRun) -> &VideoRenderEvent {
    run.events
        .last()
        .expect("worker must emit a terminal event")
}

fn failed_category(run: &WorkerRun) -> (VideoErrorCode, String) {
    match terminal(run) {
        VideoRenderEvent::Failed { error, .. } => (
            error.code,
            error.details["category"]
                .as_str()
                .unwrap_or_default()
                .to_owned(),
        ),
        other => panic!("expected failure, got {other:?}"),
    }
}

fn assert_nothing_left(run: &WorkerRun) {
    assert!(!run.output.exists(), "no output may be promoted");
    assert!(!run.partial.exists(), "partial must be cleaned");
    let manifest = manifest_path_for(&run.output).unwrap();
    assert!(!manifest.exists(), "no manifest may be written");
}

#[tokio::test]
async fn blocked_review_export_is_promoted_with_blocked_status_and_manifest() {
    // Source is 2 s black + 2 s pattern, so the export carries a black blocker.
    let run = run_qc_worker(
        "color=black:s=320x180:r=30:d=2[b];testsrc2=s=320x180:r=30:d=2[t];[b][t]concat=n=2:v=1:a=0",
        RenderWorkerHooks::default(),
        "77777777-7777-4777-8777-7777777777a1",
    )
    .await;
    let VideoRenderEvent::Completed { output, .. } = terminal(&run) else {
        panic!("blocked review export must complete: {:?}", terminal(&run));
    };
    let qc = output.qc.as_ref().expect("QC result must be attached");
    assert_eq!(qc.status, QcStatus::Blocked);
    let kinds: BTreeSet<_> = qc.findings.iter().map(|finding| finding.kind).collect();
    assert!(kinds.contains(&QcFindingKind::BlackFrames), "{kinds:?}");
    assert!(run.output.exists());
    let manifest_text = fs::read(&qc.manifest_path).unwrap();
    assert_eq!(
        super::super::qc::hex_sha256(&manifest_text),
        qc.manifest_sha256
    );
    let manifest: Value = serde_json::from_slice(&manifest_text).unwrap();
    assert_eq!(manifest["qc"]["status"], "blocked");
    assert_eq!(manifest["kind"], "review");
    assert!(manifest.get("decisions").is_none());
}

fn corrupt_partial(_: &ProcessCancellation, path: &Path) {
    fs::write(path, b"not a media file").unwrap();
}

#[tokio::test]
async fn qc_crash_fails_with_qc_unavailable_and_leaves_nothing() {
    let run = run_qc_worker(
        CLEAN_VIDEO,
        RenderWorkerHooks {
            before_qc: Some(corrupt_partial),
            ..RenderWorkerHooks::default()
        },
        "77777777-7777-4777-8777-7777777777a2",
    )
    .await;
    assert_eq!(
        failed_category(&run),
        (VideoErrorCode::QcUnavailable, "qc_unavailable".to_owned())
    );
    assert_nothing_left(&run);
}

#[tokio::test]
async fn qc_timeout_fails_with_qc_unavailable_and_leaves_nothing() {
    let run = run_qc_worker(
        CLEAN_VIDEO,
        RenderWorkerHooks {
            qc_timeout: Some(Duration::from_millis(1)),
            ..RenderWorkerHooks::default()
        },
        "77777777-7777-4777-8777-7777777777a3",
    )
    .await;
    assert_eq!(
        failed_category(&run),
        (VideoErrorCode::QcUnavailable, "qc_unavailable".to_owned())
    );
    assert_nothing_left(&run);
}

fn cancel_now(cancellation: &ProcessCancellation, _: &Path) {
    cancellation.cancel();
}

#[tokio::test]
async fn cancel_during_qc_reports_cancelled_after_cleanup() {
    let run = run_qc_worker(
        CLEAN_VIDEO,
        RenderWorkerHooks {
            before_qc: Some(cancel_now),
            ..RenderWorkerHooks::default()
        },
        "77777777-7777-4777-8777-7777777777a4",
    )
    .await;
    assert!(
        matches!(terminal(&run), VideoRenderEvent::Cancelled { .. }),
        "{:?}",
        terminal(&run)
    );
    assert_nothing_left(&run);
}

fn fail_on_persist(stage: &str) -> bool {
    stage == "persist"
}

#[tokio::test]
async fn manifest_write_failure_leaves_no_output_and_no_manifest() {
    let run = run_qc_worker(
        CLEAN_VIDEO,
        RenderWorkerHooks {
            manifest_failpoint: Some(fail_on_persist),
            ..RenderWorkerHooks::default()
        },
        "77777777-7777-4777-8777-7777777777a5",
    )
    .await;
    assert_eq!(
        failed_category(&run),
        (VideoErrorCode::ProjectIo, "manifest_write".to_owned())
    );
    assert_nothing_left(&run);
    let leftovers: Vec<_> = fs::read_dir(run.output.parent().unwrap())
        .unwrap()
        .filter_map(Result::ok)
        .filter(|entry| {
            entry
                .file_name()
                .to_string_lossy()
                .starts_with(".svp-manifest-")
        })
        .collect();
    assert!(leftovers.is_empty(), "manifest temp file must be removed");
}

fn editorial_warning(state: &str) -> Vec<QcFinding> {
    vec![QcFinding::new(
        QcFindingKind::RepeatedAsset,
        QcSeverity::Warning,
        QcSource::Editorial,
        "66666666-6666-4666-8666-6666666666c1",
        QcRange {
            start_us: 1_000_000,
            end_us: 2_000_000,
        },
        "The same shot is used again shortly after its last use".to_owned(),
        state,
    )]
}

#[tokio::test]
async fn editorial_findings_are_recorded_in_the_manifest() {
    let run = run_qc_worker_with(
        CLEAN_VIDEO,
        RenderWorkerHooks::default(),
        "77777777-7777-4777-8777-7777777777a6",
        editorial_warning,
    )
    .await;
    let VideoRenderEvent::Completed { output, .. } = terminal(&run) else {
        panic!("export must complete: {:?}", terminal(&run));
    };
    let qc = output.qc.as_ref().expect("QC result must be attached");
    assert_eq!(qc.status, QcStatus::Warnings);
    let manifest: Value = serde_json::from_slice(&fs::read(&qc.manifest_path).unwrap()).unwrap();
    let expected = &editorial_warning(STATE)[0];
    let findings = manifest["qc"]["findings"].as_array().unwrap();
    assert_eq!(findings.len(), 1);
    assert_eq!(findings[0]["findingId"], expected.finding_id);
    assert_eq!(findings[0]["source"], "editorial");
    assert_eq!(manifest["editorial"]["evaluatorVersion"], "editorial-v1");
    assert!(super::super::qc::is_sha256_hex(
        manifest["editorial"]["evaluationSha256"].as_str().unwrap()
    ));
    assert_eq!(manifest["project"]["revisionStateHash"], STATE);
    assert!(manifest["toolchainId"]
        .as_str()
        .unwrap()
        .starts_with("ffmpeg-"));
    assert_eq!(manifest["inputs"].as_array().unwrap().len(), 1);
    assert!(super::super::qc::is_sha256_hex(
        manifest["inputs"][0]["contentSha256"].as_str().unwrap()
    ));
}

#[tokio::test]
async fn same_revision_rendered_twice_has_the_same_manifest_except_timestamp_and_bytes() {
    let workspace = tempdir().unwrap();
    let programs = bundled_programs(workspace.path());
    let source = make_fixture(workspace.path(), "source", CLEAN_VIDEO, CLEAN_AUDIO);
    let plan_id = "77777777-7777-4777-8777-7777777777a7";
    let mut manifests = Vec::new();
    for overwrite in [false, true] {
        let (output, _, events) = render_once(
            workspace.path(),
            &programs,
            &source,
            plan_id,
            overwrite,
            RenderWorkerHooks::default(),
            &editorial_warning,
        )
        .await;
        let Some(VideoRenderEvent::Completed { .. }) = events.last() else {
            panic!("render must complete: {:?}", events.last());
        };
        let text = fs::read(manifest_path_for(&output).unwrap()).unwrap();
        manifests.push(serde_json::from_slice::<Value>(&text).unwrap());
    }
    let normalize = |manifest: &Value| {
        let mut copy = manifest.clone();
        copy["createdAt"] = Value::Null;
        // Encoder bytes may differ between runs; the digest is recorded, not compared.
        copy["output"]["sha256"] = Value::Null;
        copy["output"]["sizeBytes"] = Value::Null;
        copy
    };
    assert_eq!(normalize(&manifests[0]), normalize(&manifests[1]));
    assert_eq!(
        manifests[0]["renderPlanSha256"],
        manifests[1]["renderPlanSha256"]
    );
    assert!(super::super::qc::is_sha256_hex(
        manifests[1]["output"]["sha256"].as_str().unwrap()
    ));
}

#[tokio::test]
async fn missing_ffmpeg_binary_makes_qc_unavailable_without_leaking_paths() {
    let workspace = tempdir().unwrap();
    let secret = workspace.path().join("private-user-clip.mp4");
    fs::write(&secret, b"not media").unwrap();
    let programs = MediaPrograms::explicit(
        OsString::from("missing-private-ffmpeg-secret"),
        OsString::from("missing-private-ffprobe-secret"),
    );
    let error = analyze_output(
        &programs,
        ProcessCancellation::new(),
        &secret,
        &config(None),
        &[],
        (320, 180),
        STATE,
    )
    .await
    .expect_err("a missing binary must never pass QC");
    assert_eq!(error.code, VideoErrorCode::QcUnavailable);
    assert_eq!(error.details["reason"], "spawn");
    let text = serde_json::to_string(&error).unwrap();
    assert!(!text.contains("private-user-clip") && !text.contains("missing-private"));
}

fn fail_on_write(stage: &str) -> bool {
    // Same failure the OS reports when the disk is full mid-write.
    stage == "write"
}

#[tokio::test]
async fn disk_full_while_writing_the_manifest_leaves_no_output() {
    let run = run_qc_worker(
        CLEAN_VIDEO,
        RenderWorkerHooks {
            manifest_failpoint: Some(fail_on_write),
            ..RenderWorkerHooks::default()
        },
        "77777777-7777-4777-8777-7777777777a8",
    )
    .await;
    assert_eq!(
        failed_category(&run),
        (VideoErrorCode::ProjectIo, "manifest_write".to_owned())
    );
    assert_nothing_left(&run);
}

#[test]
fn render_qc_and_delivery_paths_have_no_network_dependency() {
    // Offline behaviour: export, QC, manifest, review record and delivery are
    // local-only. Guard the modules against acquiring a network client.
    for (name, source) in [
        ("qc.rs", include_str!("../qc.rs")),
        ("render_qc.rs", include_str!("../render_qc.rs")),
        ("render_manifest.rs", include_str!("../render_manifest.rs")),
        ("review_record.rs", include_str!("../review_record.rs")),
        ("delivery.rs", include_str!("../delivery.rs")),
        ("crash_report.rs", include_str!("../../crash_report.rs")),
    ] {
        for forbidden in ["reqwest", "rights::net", "TcpStream", "http://", "https://"] {
            assert!(
                !source.contains(forbidden),
                "{name} must not use {forbidden}"
            );
        }
    }
}
