import test from "node:test";
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { mkdtempSync, mkdirSync, readFileSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import {
  contained,
  command,
  context,
  makeContainedDirectory,
  rejectConfig,
  validateSymbols,
  hashFile,
  parseCargo,
  sourceInventory,
  TARGET,
  TEST_ARGV,
  validateElf,
  validateEnvironment,
  validateExits,
  validateToolchain,
  verifyManifest,
  walk,
} from "../collect-glib-evidence.mjs";

function fixture(t) {
  const root = mkdtempSync(join(tmpdir(), "glib-capture-"));
  t.after(() => rmSync(root, { force: true, recursive: true }));
  const build = join(root, TARGET, "debug/build");
  const out = join(build, "glib-fixture/out");
  mkdirSync(out, { recursive: true });
  const executable = join(root, TARGET, "debug/deps/library-hash");
  mkdirSync(join(root, TARGET, "debug/deps"));
  writeFileSync(executable, "fixture only; never executed");
  const script = {
    reason: "build-script-executed",
    package_id: "registry+fixture#glib@0.1.0",
    out_dir: out,
  };
  const artifact = {
    reason: "compiler-artifact",
    package_id: "path+fixture#desktop@0.1.0",
    target: { name: "supa_video_desktop_lib", kind: ["staticlib", "cdylib", "rlib"] },
    profile: { test: true, opt_level: "0", debuginfo: 2, debug_assertions: true },
    features: ["default", "desktop-runtime", "tauri-ipc-test"],
    executable,
    filenames: [executable],
    fresh: false,
  };
  const finished = { reason: "build-finished", success: true };
  const parse = (messages = [script, artifact, finished]) =>
    parseCargo(
      messages
        .map((message) => (typeof message === "string" ? message : JSON.stringify(message)))
        .join("\n"),
      artifact.package_id,
      artifact.features,
    );
  return { root, build, out, executable, script, artifact, finished, parse };
}

test("selects the exact Cargo package/library test, retaining same-job reuse", (t) => {
  const f = fixture(t);
  const unrelated = { ...f.artifact, package_id: "other-package" };
  const release = { ...f.artifact, profile: { ...f.artifact.profile, test: false } };
  f.artifact.fresh = true;
  const parsed = f.parse([
    f.script,
    unrelated,
    release,
    f.artifact,
    f.finished,
    "running 1 test",
    "test result: ok",
  ]);
  assert.equal(parsed.selected.executable, f.executable);
  assert.equal(parsed.selected.fresh, true);
  assert.equal(parsed.buildFinished, true);
  assert.equal(contained(join(f.root, TARGET, "debug"), parsed.selected.executable), f.executable);
});

test("fails closed on missing, duplicate, malformed or incomplete Cargo output", (t) => {
  const f = fixture(t);
  for (const messages of [
    [f.script, f.finished],
    [f.script, f.artifact, f.artifact, f.finished],
    [f.script, f.artifact],
    [f.script, f.artifact, { ...f.finished, success: false }],
    [f.artifact, f.finished],
    ["{broken"],
    [{ reason: "compiler-artifact" }, f.finished],
    [{ ...f.script, out_dir: "relative/out" }, f.artifact, f.finished],
    [f.script, f.artifact, f.finished, f.finished],
    [{ reason: "unexpected" }, f.finished],
  ])
    assert.throws(() => f.parse(messages));
});

test("rejects wrong feature/profile/executable identity rather than guessing filenames", (t) => {
  const f = fixture(t);
  for (const change of [
    { features: ["default"] },
    { executable: null },
    { executable: "relative" },
    { filenames: [] },
    { fresh: undefined },
    { profile: { ...f.artifact.profile, opt_level: "3" } },
    { profile: { ...f.artifact.profile, debuginfo: 0 } },
    { target: { ...f.artifact.target, kind: ["bin"] } },
    { package_id: "wrong" },
  ])
    assert.throws(() => f.parse([f.script, { ...f.artifact, ...change }, f.finished]));
});

test("requires both actual process exits even with a successful build-finished", () => {
  assert.deepEqual(validateExits("0 0\n"), { cargo: 0, tee: 0 });
  for (const text of ["101 0\n", "0 1\n", "1 1\n", "", "0", "0 0\n0 0", "0 0 extra"])
    assert.throws(() => validateExits(text));
});

test("inventories reported sources plus independently found same-job extras", (t) => {
  const f = fixture(t);
  writeFileSync(join(f.out, "one.rs"), "VariantStrIter");
  mkdirSync(join(f.out, "nested"));
  writeFileSync(join(f.out, "nested/two.rs"), "array_iter_str");
  const extra = join(f.build, "clippy-extra/out");
  mkdirSync(extra, { recursive: true });
  writeFileSync(join(extra, "extra.rs"), "// generated by the earlier Clippy step");
  const sources = sourceInventory(f.root, [f.script]);
  assert.equal(sources.length, 3);
  assert.equal(sources.filter((source) => source.origin === "reported-build-script").length, 2);
  assert.equal(
    sources.filter((source) => source.origin === "same-job-debug-build-extra").length,
    1,
  );
  for (const source of sources) assert.equal(source.sha256, hashFile(join(f.root, source.path)));
});

test("missing reported directories and empty inventories cannot pass", (t) => {
  const f = fixture(t);
  assert.throws(() => sourceInventory(f.root, [f.script]), /Empty/);
  assert.throws(() =>
    sourceInventory(f.root, [{ ...f.script, out_dir: join(f.build, "missing") }]),
  );
  writeFileSync(join(f.out, "one.rs"), "// generated");
  assert.throws(() => sourceInventory(f.root, [f.script, f.script]), /Duplicate/);
  assert.throws(() => sourceInventory(f.root, [{ ...f.script, out_dir: f.root }]), /escape/);
});

test("rejects absolute escapes, traversal, directories as files and release replacements", (t) => {
  const f = fixture(t);
  assert.throws(() => contained(f.out, "../../../../outside.rs"), /escape/);
  assert.throws(() => contained(f.out, resolve(f.root, "outside.rs")), /escape/);
  assert.throws(() => contained(f.root, f.out), /Nonregular/);
  assert.throws(
    () => contained(join(f.root, TARGET, "debug"), join(f.root, TARGET, "release/library")),
    /escape/,
  );
});

test("rejects symlinks even pointing within the build tree (Windows junction fixture)", (t) => {
  const f = fixture(t);
  writeFileSync(join(f.out, "one.rs"), "// generated");
  const link = join(f.build, "linked");
  symlinkSync(f.out, link, process.platform === "win32" ? "junction" : "dir");
  assert.throws(() => contained(f.build, join(link, "one.rs")), /Symlink/);
  assert.throws(() => sourceInventory(f.root, [f.script]), /Symlink|Nonregular/);
});

test("manifest verifies bytes and rejects tampering, omissions, additions and duplicates", (t) => {
  const f = fixture(t);
  const payload = join(f.root, "payload");
  mkdirSync(payload);
  writeFileSync(join(payload, "one.txt"), "original");
  const entries = [{ path: "one.txt", size: 8, sha256: hashFile(join(payload, "one.txt")) }];
  verifyManifest(payload, entries);
  assert.throws(() => verifyManifest(payload, []), /Manifest/);
  assert.throws(() => verifyManifest(payload, [...entries, ...entries]), /Manifest/);
  assert.throws(() => verifyManifest(payload, [{ ...entries[0], path: "../one.txt" }]), /Manifest/);
  writeFileSync(join(payload, "one.txt"), "tampered");
  assert.throws(() => verifyManifest(payload, entries), /hash/);
  writeFileSync(join(payload, "one.txt"), "original");
  writeFileSync(join(payload, "extra.txt"), "extra");
  assert.throws(() => verifyManifest(payload, entries), /Manifest/);
  assert.equal(walk(payload).length, 2);
});

test("requires exact compiler identity and rejects overrides without dumping values", () => {
  const rustc =
    "release: 1.98.1\ncommit-hash: 48a229cea0123456789\nhost: x86_64-unknown-linux-gnu\n";
  validateToolchain(rustc);
  for (const text of [
    rustc.replace("1.98.1", "1.97.1"),
    rustc.replace("48a229cea", "000000000"),
    rustc.replace("x86_64", "aarch64"),
  ])
    assert.throws(() => validateToolchain(text));
  assert.deepEqual(validateEnvironment({ CARGO_INCREMENTAL: "0", GITHUB_TOKEN: "not captured" }), {
    CARGO_INCREMENTAL: "0",
  });
  for (const key of [
    "RUSTFLAGS",
    "RUSTDOCFLAGS",
    "RUSTC_WRAPPER",
    "RUSTC_WORKSPACE_WRAPPER",
    "RUSTC_BOOTSTRAP",
    "CARGO_ENCODED_RUSTFLAGS",
    "CARGO_TARGET_DIR",
    "CARGO_BUILD_TARGET",
    "CARGO_PROFILE_TEST_DEBUG",
  ])
    assert.throws(
      () => validateEnvironment({ [key]: "private value" }),
      (error) => error.message.includes(key) && !error.message.includes("private value"),
    );
  assert.throws(() => validateEnvironment({ RUSTUP_TOOLCHAIN: "stable" }));
  validateEnvironment({ RUSTUP_TOOLCHAIN: "1.98.1-x86_64-unknown-linux-gnu" });
});

test("requires unstripped ELF64 x86-64, full symbol/debug sections and GNU build ID", () => {
  const reports = {
    file: "ELF 64-bit LSB pie executable, x86-64, with debug_info, not stripped",
    header: "Class: ELF64\nMachine: Advanced Micro Devices X86-64",
    sections: "  .symtab SYMTAB\n  .debug_info PROGBITS",
    notes: "GNU 0x00000014 NT_GNU_BUILD_ID (unique build ID bitstring)\nBuild ID: abc123",
  };
  assert.equal(validateElf(reports), "abc123");
  for (const field of Object.keys(reports))
    assert.throws(() => validateElf({ ...reports, [field]: "" }));
});

test("missing/failed inspection commands and empty symbols never become no-match success", (t) => {
  const { root } = fixture(t);
  assert.throws(() => command(root, join(root, "missing-tool"), []), /missing-tool.*failed/);
  assert.throws(() => command(root, process.execPath, ["-e", "process.exit(7)"]), /failed \(7\)/);
  const output = join(root, "symbols.txt");
  const receipt = command(
    root,
    process.execPath,
    ["-e", "process.stdout.write('00001234 T unrelated_symbol\\n')"],
    output,
  );
  assert.equal(receipt.status, 0);
  validateSymbols(readFileSync(output, "utf8"));
  for (const text of ["", " \n", "nm: no symbols"]) assert.throws(() => validateSymbols(text));
});

test("scratch creation refuses symlinked parents and Cargo config is not silently ignored", (t) => {
  const { root, out } = fixture(t);
  makeContainedDirectory(root, "scratch/nested");
  assert.equal(contained(root, "scratch/nested", "directory"), join(root, "scratch/nested"));
  symlinkSync(out, join(root, "linked"), process.platform === "win32" ? "junction" : "dir");
  assert.throws(() => makeContainedDirectory(root, "linked/escape"), /Symlink/);
  assert.throws(() => makeContainedDirectory(root, "../escape"), /escape/);
  const home = join(root, "cargo-home");
  mkdirSync(home);
  writeFileSync(join(home, "config.toml"), "[build]\ntarget = 'unexpected'");
  assert.throws(() => rejectConfig(root, home), /Unsupported Cargo config/);
});

test("provenance distinguishes PR merge checkout context without copying secrets", (t) => {
  const { root } = fixture(t);
  const event = join(root, "event.json");
  writeFileSync(
    event,
    JSON.stringify({
      number: 42,
      pull_request: {
        head: { sha: "head" },
        base: { sha: "base" },
        merge_commit_sha: "merge",
        body: "not retained",
      },
    }),
  );
  const env = {
    GITHUB_REPOSITORY: "owner/repo",
    GITHUB_SHA: "merge",
    GITHUB_REF: "refs/pull/42/merge",
    GITHUB_EVENT_NAME: "pull_request",
    GITHUB_WORKFLOW_SHA: "workflow",
    GITHUB_WORKFLOW_REF: "owner/repo/.github/workflows/ci.yml@refs/pull/42/merge",
    GITHUB_RUN_ID: "123",
    GITHUB_RUN_ATTEMPT: "2",
    GITHUB_JOB: "rust",
    GITHUB_SERVER_URL: "https://github.com",
    RUNNER_OS: "Linux",
    RUNNER_ARCH: "X64",
    ImageOS: "ubuntu24",
    ImageVersion: "fixture",
    GITHUB_EVENT_PATH: event,
    GITHUB_TOKEN: "not retained",
  };
  const provenance = context(env);
  assert.equal(provenance.GITHUB_SHA, "merge");
  assert.equal(provenance.pullRequest.headSha, "head");
  assert.equal(provenance.runUrl, "https://github.com/owner/repo/actions/runs/123/attempts/2");
  assert.doesNotMatch(JSON.stringify(provenance), /not retained/);
  assert.throws(() => context({ ...env, GITHUB_RUN_ATTEMPT: "" }), /Missing provenance/);
  assert.throws(() => context({ ...env, GITHUB_JOB: "windows" }), /Unexpected hosted job/);
});

test("actual workflow pipeline preserves Cargo failure before tee failure", (t) => {
  const { root } = fixture(t);
  const workflow = readFileSync(new URL("../../.github/workflows/ci.yml", import.meta.url), "utf8");
  const block = workflow
    .split("        id: all_feature_tests\n")[1]
    .split("        run: |\n")[1]
    .split("\n\n")[0]
    .replace(/^          /gm, "");
  mkdirSync(join(root, ".cache/p1-security/hosted-glib"), { recursive: true });
  for (const [cargoExit, teeExit] of [
    [0, 0],
    [101, 0],
    [0, 9],
    [101, 9],
  ]) {
    const result = spawnSync("bash", ["--noprofile", "--norc", "-e", "-o", "pipefail"], {
      cwd: root,
      encoding: "utf8",
      input: `cargo() { printf 'test output\\n'; return ${cargoExit}; }\ntee() { cat; return ${teeExit}; }\n${block}\n`,
      timeout: 10000,
    });
    assert.ifError(result.error);
    assert.equal(result.status, cargoExit || teeExit);
    assert.match(result.stdout, /test output/);
    assert.equal(
      readFileSync(join(root, ".cache/p1-security/hosted-glib/test-exits.txt"), "utf8").trim(),
      `${cargoExit} ${teeExit}`,
    );
  }
});

test("workflow retains gates and fail-closed capture wiring only in Linux Rust job", () => {
  const workflow = readFileSync(new URL("../../.github/workflows/ci.yml", import.meta.url), "utf8");
  const rust = workflow.split("\n  rust:\n")[1].split("\n  windows:\n")[0];
  assert.match(rust, /timeout-minutes: 30/);
  assert.match(rust, /toolchain: 1\.98\.1/);
  assert.match(rust, /cache-targets: false/);
  assert.ok(rust.indexOf("collect-glib-evidence.mjs prepare") < rust.indexOf("cargo clippy"));
  assert.ok(rust.includes(`cargo ${TEST_ARGV.join(" ")} | tee`));
  assert.match(rust, /pipeline_status=\("\$\{PIPESTATUS\[@\]\}"\)/);
  assert.match(
    rust,
    /if \(\( pipeline_status\[0\] != 0 \)\); then exit "\$\{pipeline_status\[0\]\}"; fi/,
  );
  assert.match(rust, /exit "\$\{pipeline_status\[1\]\}"/);
  assert.equal((rust.match(/cargo test --release --locked/g) ?? []).length, 5);
  assert.equal((rust.match(/-- --exact --nocapture/g) ?? []).length, 5);
  assert.match(
    rust,
    /cargo clippy --locked --all-targets --all-features --manifest-path apps\/desktop\/src-tauri\/Cargo.toml -- -D warnings/,
  );
  assert.ok(
    rust.indexOf("collect-glib-evidence.mjs collect") >
      rust.indexOf("restart_recovery_selection_across_10k_jobs_meets_release_budget"),
  );
  assert.match(rust, /!cancelled\(\) && steps\.all_feature_tests\.outcome == 'success'/);
  assert.match(rust, /!cancelled\(\) && steps\.glib_capture\.outcome == 'success'/);
  assert.match(rust, /actions\/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a/);
  assert.match(rust, /if-no-files-found: error/);
  assert.match(rust, /retention-days: 30/);
  assert.match(rust, /overwrite: false/);
  assert.doesNotMatch(rust, /continue-on-error|--target |--no-default-features|permissions:/);
});
