// GENERATED by scripts/generate-motion-presets.mjs from diffusion-studio-2 lib/motion-presets.data.ts: do not edit.
// Units: x/y offsets in layer widths/heights from rest, scale and opacity multipliers of rest,
// rotation degrees added to rest; times in microseconds from the preset start.
import type { MotionPresetData } from "./motion-presets.js";

export const MOTION_PRESET_DATA = {
  cursorDrag: {
    source: "diffusion-studio-2 reference/analysed/headshot.motion.video.json (cursor)",
    durationMicroseconds: 466700,
    tracks: {
      x: [
        {
          timeMicroseconds: 0,
          value: -2.4779,
        },
        {
          timeMicroseconds: 266600,
          value: -2.4779,
          easing: {
            kind: "cubicBezier",
            x1: 1,
            y1: 1.3679,
            x2: 0.4523,
            y2: 0.6958,
          },
        },
        {
          timeMicroseconds: 446400,
          value: 0,
        },
      ],
      y: [
        {
          timeMicroseconds: 0,
          value: 2.1089,
        },
        {
          timeMicroseconds: 265700,
          value: 2.1089,
          easing: {
            kind: "cubicBezier",
            x1: 0.8552,
            y1: 1.1939,
            x2: 0.3926,
            y2: 0.6441,
          },
        },
        {
          timeMicroseconds: 466700,
          value: 0,
        },
      ],
      scale: [
        {
          timeMicroseconds: 0,
          value: 1.2646,
        },
        {
          timeMicroseconds: 237700,
          value: 1.2646,
          easing: {
            kind: "cubicBezier",
            x1: 0.7402,
            y1: 0.2697,
            x2: 0.1668,
            y2: -0.4097,
          },
        },
        {
          timeMicroseconds: 433300,
          value: 0.8158,
          easing: {
            kind: "cubicBezier",
            x1: 0,
            y1: 0,
            x2: 0.4217,
            y2: 0.4964,
          },
        },
        {
          timeMicroseconds: 466700,
          value: 1,
        },
      ],
      rotation: [
        {
          timeMicroseconds: 0,
          value: 2.0634,
        },
        {
          timeMicroseconds: 366700,
          value: 2.0634,
        },
        {
          timeMicroseconds: 400000,
          value: 0,
        },
      ],
      opacity: [
        {
          timeMicroseconds: 0,
          value: 0.0014,
          easing: {
            kind: "cubicBezier",
            x1: 0.3352,
            y1: 0.4361,
            x2: 0.4795,
            y2: 0.6179,
          },
        },
        {
          timeMicroseconds: 221100,
          value: 1,
        },
        {
          timeMicroseconds: 400000,
          value: 1,
          easing: {
            kind: "cubicBezier",
            x1: 0,
            y1: 0.4169,
            x2: 0.4061,
            y2: 0.7517,
          },
        },
        {
          timeMicroseconds: 466700,
          value: 1,
        },
      ],
    },
  },
  pop: {
    source: "diffusion-studio-2 reference/analysed/headshot.motion.video.json (whats-card)",
    durationMicroseconds: 200000,
    tracks: {
      x: [
        {
          timeMicroseconds: 0,
          value: 0.5633,
          easing: {
            kind: "cubicBezier",
            x1: 0.0268,
            y1: 0.6758,
            x2: 0.4616,
            y2: 0.9309,
          },
        },
        {
          timeMicroseconds: 200000,
          value: 0,
        },
      ],
      y: [
        {
          timeMicroseconds: 0,
          value: -0.5156,
        },
        {
          timeMicroseconds: 33300,
          value: -0.2072,
          easing: {
            kind: "cubicBezier",
            x1: 0.4064,
            y1: 0.0375,
            x2: 0.5612,
            y2: 1.0188,
          },
        },
        {
          timeMicroseconds: 100000,
          value: -0.0844,
          easing: {
            kind: "cubicBezier",
            x1: 0.1826,
            y1: 0.1329,
            x2: 0.2521,
            y2: 0.8739,
          },
        },
        {
          timeMicroseconds: 200000,
          value: 0,
        },
      ],
      scale: [
        {
          timeMicroseconds: 0,
          value: 0.5462,
          easing: {
            kind: "preset",
            name: "strong",
          },
        },
        {
          timeMicroseconds: 33300,
          value: 1,
        },
      ],
      rotation: [
        {
          timeMicroseconds: 0,
          value: -1.2227,
        },
        {
          timeMicroseconds: 33300,
          value: -2.6206,
          easing: {
            kind: "cubicBezier",
            x1: 0.4104,
            y1: 0.5422,
            x2: 0.7337,
            y2: 0.8439,
          },
        },
        {
          timeMicroseconds: 200000,
          value: 0,
        },
      ],
      opacity: [
        {
          timeMicroseconds: 0,
          value: 1,
        },
      ],
    },
  },
  rockSlide: {
    source: "diffusion-studio-2 reference/analysed/headshot.motion.video.json (rock-card)",
    durationMicroseconds: 200000,
    tracks: {
      x: [
        {
          timeMicroseconds: 0,
          value: 0.1264,
        },
        {
          timeMicroseconds: 33400,
          value: 0.0696,
          easing: {
            kind: "cubicBezier",
            x1: 0.2309,
            y1: 0.4352,
            x2: 0.5572,
            y2: 0.991,
          },
        },
        {
          timeMicroseconds: 200000,
          value: 0,
        },
      ],
      y: [
        {
          timeMicroseconds: 0,
          value: 0.3148,
        },
        {
          timeMicroseconds: 33400,
          value: 0.13,
          easing: {
            kind: "cubicBezier",
            x1: 0.5636,
            y1: 0.9728,
            x2: 0.3205,
            y2: 0.4983,
          },
        },
        {
          timeMicroseconds: 166700,
          value: 0,
        },
      ],
      scale: [
        {
          timeMicroseconds: 0,
          value: 1.3698,
          easing: {
            kind: "preset",
            name: "easeIn",
          },
        },
        {
          timeMicroseconds: 66700,
          value: 1.1952,
          easing: {
            kind: "cubicBezier",
            x1: 0,
            y1: 0.2373,
            x2: 0.5506,
            y2: 0.8743,
          },
        },
        {
          timeMicroseconds: 166700,
          value: 1.0307,
        },
        {
          timeMicroseconds: 200000,
          value: 1,
        },
      ],
      rotation: [
        {
          timeMicroseconds: 0,
          value: -3.2642,
        },
        {
          timeMicroseconds: 33400,
          value: -0.2085,
        },
        {
          timeMicroseconds: 66700,
          value: 2.3113,
          easing: {
            kind: "preset",
            name: "snappy",
          },
        },
        {
          timeMicroseconds: 133400,
          value: 0.8043,
          easing: {
            kind: "preset",
            name: "snappy",
          },
        },
        {
          timeMicroseconds: 200000,
          value: 0,
        },
      ],
      opacity: [
        {
          timeMicroseconds: 0,
          value: 0.7426,
        },
        {
          timeMicroseconds: 33400,
          value: 1,
        },
        {
          timeMicroseconds: 100500,
          value: 1,
        },
      ],
    },
  },
  slam: {
    source: "diffusion-studio-2 reference/analysed/supah-coder-launch.motion.video.json (12-e1)",
    durationMicroseconds: 270800,
    tracks: {
      x: [
        {
          timeMicroseconds: 0,
          value: -0.169,
          easing: {
            kind: "cubicBezier",
            x1: 0.2509,
            y1: 1.2201,
            x2: 0.5346,
            y2: 0.9369,
          },
        },
        {
          timeMicroseconds: 181500,
          value: 0,
        },
      ],
      y: [
        {
          timeMicroseconds: 0,
          value: -0.0392,
          easing: {
            kind: "cubicBezier",
            x1: 0.2468,
            y1: 0.7757,
            x2: 0.4822,
            y2: 0.7053,
          },
        },
        {
          timeMicroseconds: 87000,
          value: 0,
        },
      ],
      scale: [
        {
          timeMicroseconds: 0,
          value: 1.3309,
          easing: {
            kind: "cubicBezier",
            x1: 0.1969,
            y1: 0.9238,
            x2: 0.1095,
            y2: 0.92,
          },
        },
        {
          timeMicroseconds: 270800,
          value: 1,
        },
      ],
      rotation: [
        {
          timeMicroseconds: 0,
          value: 1.1132,
          easing: {
            kind: "cubicBezier",
            x1: 0.0003,
            y1: 0.2871,
            x2: 0.6907,
            y2: 1.3395,
          },
        },
        {
          timeMicroseconds: 266700,
          value: 0,
        },
      ],
      opacity: [
        {
          timeMicroseconds: 0,
          value: 1,
        },
      ],
    },
  },
  tiltIn: {
    source: "diffusion-studio-2 reference/analysed/headshot.motion.video.json (a-tag)",
    durationMicroseconds: 233300,
    tracks: {
      x: [
        {
          timeMicroseconds: 0,
          value: 0.544,
        },
        {
          timeMicroseconds: 33300,
          value: 0.544,
          easing: {
            kind: "cubicBezier",
            x1: 0.6315,
            y1: 0.9154,
            x2: 0.6494,
            y2: 0.9109,
          },
        },
        {
          timeMicroseconds: 233300,
          value: 0,
        },
      ],
      y: [
        {
          timeMicroseconds: 0,
          value: -1.1006,
        },
        {
          timeMicroseconds: 33300,
          value: -1.1006,
          easing: {
            kind: "cubicBezier",
            x1: 0.1511,
            y1: 0.3976,
            x2: 0.5793,
            y2: 1.012,
          },
        },
        {
          timeMicroseconds: 233300,
          value: 0,
        },
      ],
      scale: [
        {
          timeMicroseconds: 0,
          value: 0.9817,
        },
        {
          timeMicroseconds: 113300,
          value: 0.9817,
          easing: {
            kind: "cubicBezier",
            x1: 0.3815,
            y1: 0.6122,
            x2: 0.7123,
            y2: 0.9252,
          },
        },
        {
          timeMicroseconds: 233300,
          value: 1,
        },
      ],
      rotation: [
        {
          timeMicroseconds: 0,
          value: -23.1718,
        },
        {
          timeMicroseconds: 33300,
          value: -23.1718,
        },
        {
          timeMicroseconds: 66700,
          value: -9.2673,
        },
        {
          timeMicroseconds: 100000,
          value: -8.7356,
          easing: {
            kind: "cubicBezier",
            x1: 0.2408,
            y1: 0.6357,
            x2: 0.6413,
            y2: 0.8911,
          },
        },
        {
          timeMicroseconds: 233300,
          value: 0,
        },
      ],
      opacity: [
        {
          timeMicroseconds: 0,
          value: 0.0572,
        },
        {
          timeMicroseconds: 33300,
          value: 1,
        },
        {
          timeMicroseconds: 66700,
          value: 1,
        },
        {
          timeMicroseconds: 100700,
          value: 1,
        },
      ],
    },
  },
} as const satisfies Record<string, MotionPresetData>;
