Set-StrictMode -Version 2.0

function Get-WavDuration([string]$Path) {
    $ffprobe = Get-Command ffprobe.exe -ErrorAction SilentlyContinue
    if (-not $ffprobe) { $ffprobe = Get-Command ffprobe -ErrorAction SilentlyContinue }
    if (-not $ffprobe) { throw 'FFprobe is required for fixture duration metadata.' }
    if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) { throw "Cannot probe absent WAV: $Path" }
    $result = Invoke-External $ffprobe.Source @('-v','error','-show_entries','format=duration','-of','default=noprint_wrappers=1:nokey=1',$Path) 30 $script:Scratch 'ffprobe-duration'
    if ($result.exitCode -ne 0 -or $result.timedOut -or -not $result.stdout.Trim()) { throw "FFprobe could not read WAV duration: $Path" }
    return [double]::Parse($result.stdout.Trim(), [Globalization.CultureInfo]::InvariantCulture)
}

function ConvertTo-Ssml([string]$Text, [string]$Prefix) {
    $tokens = [regex]::Matches($Text, "[A-Za-z0-9][A-Za-z0-9'\.\-]*|[$][0-9,.]+") | ForEach-Object { $_.Value }
    if ($tokens.Count -eq 0) { throw "No speech tokens were declared for $Prefix." }
    $builder = New-Object Text.StringBuilder
    [void]$builder.Append("<speak version='1.0' xml:lang='en-US'><prosody rate='-5%'>")
    for ($index=0; $index -lt $tokens.Count; $index++) {
        $escaped = [Security.SecurityElement]::Escape($tokens[$index])
        [void]$builder.Append("<mark name='$Prefix-$('{0:D4}' -f $index)'/>$escaped ")
    }
    [void]$builder.Append('</prosody></speak>')
    return [ordered]@{ ssml=$builder.ToString(); tokens=@($tokens) }
}

function Initialize-SpeechSynthesizer {
    Add-Type -AssemblyName System.Speech
    $code = @'
using System;
using System.Collections.Generic;
using System.Speech.AudioFormat;
using System.Speech.Synthesis;
public sealed class BookmarkRow { public string Name; public double Seconds; }
public static class SpikeSpeech {
  public static BookmarkRow[] Render(string ssml, string path, string voice) {
    var rows = new List<BookmarkRow>();
    using (var synthesizer = new SpeechSynthesizer()) {
      synthesizer.SelectVoice(voice);
      synthesizer.SetOutputToWaveFile(path, new SpeechAudioFormatInfo(16000, AudioBitsPerSample.Sixteen, AudioChannel.Mono));
      synthesizer.BookmarkReached += (sender, args) => rows.Add(new BookmarkRow { Name=args.Bookmark, Seconds=args.AudioPosition.TotalSeconds });
      synthesizer.SpeakSsml(ssml);
    }
    return rows.ToArray();
  }
}
'@
    if (-not ('SpikeSpeech' -as [type])) { Add-Type -TypeDefinition $code -ReferencedAssemblies @([System.Speech.Synthesis.SpeechSynthesizer].Assembly.Location) }
}

function Get-RecipeFixture($Recipe, [string]$Id) {
    $fixture = @($Recipe.fixtures | Where-Object { $_.id -eq $Id })
    if ($fixture.Count -ne 1) { throw "Fixture recipe must declare exactly one '$Id' fixture." }
    return $fixture[0]
}

function Test-Effect($Turn, [string]$Name) {
    return @($Turn.effects) -contains $Name
}

function Assert-FixtureCondition([bool]$Condition, [string]$Label, $Assertions) {
    if (-not $Condition) { throw "Fixture validation failed: $Label" }
    $Assertions.Add($Label)
}

function Test-SortedBookmarkTimes($Bookmarks) {
    $previous = -1.0
    foreach ($bookmark in @($Bookmarks)) {
        if ([double]$bookmark.seconds -lt $previous) { return $false }
        $previous = [double]$bookmark.seconds
    }
    return $true
}

function Get-SentinelPositions($Bookmarks, [string]$FirstWord, [string]$SecondWord) {
    $positions = @()
    $ordered = @($Bookmarks)
    for ($index=0; $index -lt $ordered.Count-1; $index++) {
        if ((Normalize-Transcript ([string]$ordered[$index].word)) -eq $FirstWord -and (Normalize-Transcript ([string]$ordered[$index+1].word)) -eq $SecondWord) {
            $positions += [ordered]@{
                seconds=[math]::Round([double]$ordered[$index].seconds,6)
                wordIndex=$index
                segmentIndex=$(if ($ordered[$index].Contains('segmentIndex')) { $ordered[$index].segmentIndex } else { $null })
                variantId=$(if ($ordered[$index].Contains('variantId')) { $ordered[$index].variantId } else { $null })
            }
        }
    }
    return $positions
}

function Test-RepresentativeFixtures($Fixtures, $Recipe, [bool]$LongSkipped) {
    $assertions = New-Object System.Collections.Generic.List[string]
    foreach ($name in @('jfk','clean','ugly','tiny')) {
        $fixture = $Fixtures[$name]
        Assert-FixtureCondition (Test-Path -LiteralPath $fixture.path -PathType Leaf) "$($fixture.id) audio exists" $assertions
        Assert-FixtureCondition (([string]$fixture.sha256) -match '^[0-9a-f]{64}$') "$($fixture.id) SHA-256 metadata is present" $assertions
        Assert-FixtureCondition ((Get-Sha256 $fixture.path) -eq $fixture.sha256) "$($fixture.id) SHA-256 metadata matches generated bytes" $assertions
        Assert-FixtureCondition ([math]::Abs((Get-WavDuration $fixture.path)-[double]$fixture.duration) -le 0.001) "$($fixture.id) duration metadata matches FFprobe" $assertions
    }

    $cleanRecipe = Get-RecipeFixture $Recipe 'clean-keyterms'
    $uglyRecipe = Get-RecipeFixture $Recipe 'ugly-dialogue'
    Assert-FixtureCondition ([double]$Fixtures.clean.duration -ge [double]$cleanRecipe.targetDurationSeconds[0] -and [double]$Fixtures.clean.duration -le [double]$cleanRecipe.targetDurationSeconds[1]) 'clean duration is in its declared range' $assertions
    Assert-FixtureCondition ([double]$Fixtures.ugly.duration -ge [double]$uglyRecipe.targetDurationSeconds[0] -and [double]$Fixtures.ugly.duration -le [double]$uglyRecipe.targetDurationSeconds[1]) 'ugly duration is in its declared range' $assertions
    Assert-FixtureCondition (Test-SortedBookmarkTimes $Fixtures.clean.bookmarks) 'clean bookmark words are sorted by final audio time' $assertions
    Assert-FixtureCondition (Test-SortedBookmarkTimes $Fixtures.ugly.bookmarks) 'ugly bookmark words are sorted by final audio time' $assertions
    Assert-FixtureCondition (@($Fixtures.ugly.turns).Count -eq @($uglyRecipe.turnSchedule).Count) 'every declared ugly turn is persisted' $assertions

    $turns = @($Fixtures.ugly.turns)
    for ($index=0; $index -lt $turns.Count; $index++) {
        $declared=$uglyRecipe.turnSchedule[$index]
        Assert-FixtureCondition ($turns[$index].id -eq $declared.id -and (@($turns[$index].effects)-join ',') -eq (@($declared.effects)-join ',')) "ugly turn $($index+1) identity and effects match the schedule" $assertions
        if($index -gt 0){Assert-FixtureCondition ($turns[$index].speaker -ne $turns[$index-1].speaker) "ugly speakers alternate at turn $($index+1)" $assertions}
    }
    $declaredOverlapCount = @($uglyRecipe.turnSchedule | Where-Object { [int]$_.overlapPreviousMs -gt 0 }).Count
    Assert-FixtureCondition (@($Fixtures.ugly.overlapIntervals).Count -eq $declaredOverlapCount) 'persisted overlap count matches the declared interruptions' $assertions
    foreach ($interval in @($Fixtures.ugly.overlapIntervals)) {
        $length = [double]$interval.end - [double]$interval.start
        Assert-FixtureCondition ($length -gt 0 -and $length -le [double]$uglyRecipe.maxOverlapSeconds + 0.001) "overlap $($interval.turnId) is positive and bounded" $assertions
    }
    $declaredPhoneCount = @($uglyRecipe.turnSchedule | Where-Object { Test-Effect $_ 'phone-band' }).Count
    Assert-FixtureCondition (@($Fixtures.ugly.phoneIntervals).Count -eq $declaredPhoneCount) 'persisted phone interval count matches the schedule' $assertions
    foreach ($interval in @($Fixtures.ugly.phoneIntervals)) {
        $length = [double]$interval.end - [double]$interval.start
        Assert-FixtureCondition ($length -gt 0 -and $length -le [double]$uglyRecipe.maxPhoneSectionSeconds) "phone interval $($interval.turnId) is positive and bounded" $assertions
    }
    $generationGraph=@($Fixtures.ugly.generationFilters)-join ';'
    $componentPatterns=[ordered]@{hvac='anoisesrc=';reverb='aecho=';clothingImpulses='aevalsrc=';tonalAmbience='sine=';phoneBand='highpass=.*lowpass=';clippedPeaks='asoftclip='}
    foreach ($component in $componentPatterns.Keys) {
        Assert-FixtureCondition (@($Fixtures.ugly.disturbanceComponents) -contains $component -and $generationGraph -match $componentPatterns[$component]) "required disturbance $component is present in the executed FFmpeg graph" $assertions
    }

    if ($LongSkipped) {
        Assert-FixtureCondition ($Fixtures.long.skipped -eq $true) 'long generation records an explicit skip' $assertions
    } else {
        $longRecipe = Get-RecipeFixture $Recipe 'long-stability'
        Assert-FixtureCondition (Test-Path -LiteralPath $Fixtures.long.path -PathType Leaf) 'long audio exists' $assertions
        Assert-FixtureCondition (([string]$Fixtures.long.sha256) -match '^[0-9a-f]{64}$' -and (Get-Sha256 $Fixtures.long.path) -eq $Fixtures.long.sha256) 'long SHA-256 metadata matches generated bytes' $assertions
        Assert-FixtureCondition ([math]::Abs((Get-WavDuration $Fixtures.long.path)-[double]$Fixtures.long.duration) -le 0.001) 'long duration metadata matches FFprobe' $assertions
        Assert-FixtureCondition ([math]::Abs([double]$Fixtures.long.duration-[double]$longRecipe.targetDurationSeconds) -le 0.05) 'long duration matches the declared target' $assertions
        Assert-FixtureCondition (@($Fixtures.long.joins).Count -eq (@($Fixtures.long.segments).Count-1)) 'long join count exactly matches segment transitions' $assertions
        Assert-FixtureCondition ([int]$Fixtures.long.expectedJoinCount -eq @($Fixtures.long.joins).Count) 'long persisted expected join count is exact' $assertions
        Assert-FixtureCondition (@($Fixtures.long.variants).Count -eq @($longRecipe.variantCycle).Count) 'every declared long variant identity is persisted' $assertions
        for($index=0;$index -lt @($Fixtures.long.variants).Count;$index++){
            $variant=$Fixtures.long.variants[$index]
            Assert-FixtureCondition ($variant.id -eq $longRecipe.variantCycle[$index].id) "long variant $index identity matches the recipe" $assertions
            Assert-FixtureCondition ((Get-Sha256 $variant.path) -eq $variant.sha256) "long variant $($variant.id) hash matches its audio" $assertions
        }
        $segments=@($Fixtures.long.segments);$joins=@($Fixtures.long.joins)
        Assert-FixtureCondition ([math]::Abs([double]$segments[0].start) -le 0.000001) 'long segment schedule starts at zero' $assertions
        for($index=1;$index -lt $segments.Count;$index++){
            $left=$segments[$index-1];$right=$segments[$index];$join=$joins[$index-1]
            Assert-FixtureCondition ([math]::Abs([double]$left.end-[double]$right.start) -le 0.000001) "long segment $index is contiguous" $assertions
            Assert-FixtureCondition ([math]::Abs([double]$join.seconds-[double]$right.start) -le 0.000001 -and $join.leftVariantId -eq $left.variantId -and $join.rightVariantId -eq $right.variantId) "long join $index matches adjacent variant identities and time" $assertions
            $expectedIndexes=@($join.referenceIndexes);$expectedWords=@($expectedIndexes|ForEach-Object{[string]$Fixtures.long.bookmarks[[int]$_].word})
            Assert-FixtureCondition (($expectedWords -join "`n") -eq (@($join.expectedWords) -join "`n")) "long join $index words match chronological gold" $assertions
        }
        Assert-FixtureCondition (Test-SortedBookmarkTimes $Fixtures.long.bookmarks) 'long bookmark words are sorted by final audio time' $assertions
        $sentinelWords=@((Normalize-Transcript ([string]$longRecipe.sentinel))-split ' '|Where-Object{$_})
        $recomputedSentinels=@(Get-SentinelPositions $Fixtures.long.bookmarks $sentinelWords[0] $sentinelWords[1])
        Assert-FixtureCondition (@($Fixtures.long.sentinelPositions).Count -gt 0) 'long fixture contains repeated sentinels' $assertions
        Assert-FixtureCondition ([int]$Fixtures.long.expectedSentinelCount -eq $recomputedSentinels.Count) 'long persisted sentinel count is exact' $assertions
        Assert-FixtureCondition ((@($Fixtures.long.expectedSentinelTimes)-join ',') -eq (@($recomputedSentinels|ForEach-Object{$_.seconds})-join ',')) 'long sentinel positions exactly match chronological bookmark gold' $assertions
    }
    return [ordered]@{ passed=$true; assertions=$assertions.ToArray() }
}

function New-RepresentativeFixtures([string]$PinnedSource) {
    $recipePath = Join-Path $script:EvidenceRoot 'fixture-recipe.json'
    $recipe = Get-Content -LiteralPath $recipePath -Raw | ConvertFrom-Json
    $cleanRecipe = Get-RecipeFixture $recipe 'clean-keyterms'
    $uglyRecipe = Get-RecipeFixture $recipe 'ugly-dialogue'
    $longRecipe = Get-RecipeFixture $recipe 'long-stability'
    Initialize-SpeechSynthesizer

    $ffmpegCommand = Get-Command ffmpeg.exe -ErrorAction SilentlyContinue
    if (-not $ffmpegCommand) { $ffmpegCommand = Get-Command ffmpeg -ErrorAction SilentlyContinue }
    if (-not $ffmpegCommand) { throw 'FFmpeg is required for fixture generation.' }
    $ffmpeg = $ffmpegCommand.Source
    [void](Get-WavDuration (Join-Path $PinnedSource 'test_files\asr\wav\test\jfk.wav'))
    $filters = Invoke-External $ffmpeg @('-hide_banner','-filters') 30 $script:Scratch 'ffmpeg-filters'
    if ($filters.exitCode -ne 0 -or $filters.timedOut) { throw 'FFmpeg filter discovery failed.' }
    foreach ($filter in @('amix','aecho','adelay','anoisesrc','highpass','lowpass','volume','sine','aevalsrc','asoftclip','aresample','loudnorm','apad','atrim','asetpts')) {
        if (($filters.stdout + $filters.stderr) -notmatch "\b$filter\b") { throw "Required FFmpeg filter missing: $filter" }
    }

    $fixtureDir = Join-Path $script:Scratch 'fixtures'
    New-Item -ItemType Directory -Path $fixtureDir -Force | Out-Null
    $synthesizer = New-Object System.Speech.Synthesis.SpeechSynthesizer
    try { $voices = @($synthesizer.GetInstalledVoices() | Where-Object { $_.Enabled -and $_.VoiceInfo.Culture.Name -like 'en-*' } | ForEach-Object { $_.VoiceInfo.Name } | Sort-Object -Unique) } finally { $synthesizer.Dispose() }
    if ($voices.Count -lt [int]$uglyRecipe.voiceCount) { throw 'Two distinct installed English SAPI voices are required.' }

    $jfkSource = Join-Path $PinnedSource 'test_files\asr\wav\test\jfk.wav'
    if (-not (Test-Path -LiteralPath $jfkSource -PathType Leaf)) { throw 'Pinned JFK smoke fixture is absent.' }
    $jfk = Join-Path $fixtureDir 'jfk-smoke.wav'
    Copy-Item -LiteralPath $jfkSource -Destination $jfk

    $cleanBase = 'Nemotron by NVIDIA meets AssemblyAI through FFmpeg CUDA and Vulkan on a GTX 1080. TranscriptArtifactV1 preserves exact source identity. On August 9 2026 the invoice was $1,234.56, pi was 3.14159, and the callback number was 415 555 0137. Accurate keyterms, punctuation, timing, privacy, and deterministic output matter for video dialogue.'
    $cleanText = (($cleanBase + ' ') * 2).Trim()
    $cleanSsml = ConvertTo-Ssml $cleanText 'clean'
    $clean = Join-Path $fixtureDir 'clean-keyterms.wav'
    $cleanMarks = @([SpikeSpeech]::Render($cleanSsml.ssml, $clean, $voices[0]) | ForEach-Object { [ordered]@{ name=$_.Name; seconds=[math]::Round([double]$_.Seconds,6) } })
    if ($cleanMarks.Count -ne $cleanSsml.tokens.Count) { throw 'SAPI bookmark timing was incomplete for clean-keyterms.' }
    for ($index=0; $index -lt $cleanMarks.Count; $index++) { $cleanMarks[$index].word=$cleanSsml.tokens[$index]; $cleanMarks[$index].ordinal=$index }
    $cleanDuration = Get-WavDuration $clean

    $turns = @()
    $uglyBookmarks = @()
    $overlapIntervals = @()
    $phoneIntervals = @()
    $previousEnd = 0.0
    for ($turnIndex=0; $turnIndex -lt @($uglyRecipe.turnSchedule).Count; $turnIndex++) {
        $declared = $uglyRecipe.turnSchedule[$turnIndex]
        $expectedSpeaker = if (($turnIndex % 2) -eq 0) { 'A' } else { 'B' }
        if ([string]$declared.speaker -ne $expectedSpeaker) { throw "Ugly turn schedule does not alternate at $($declared.id)." }
        if ([int]$declared.overlapPreviousMs -gt 0 -and [int]$declared.gapAfterPreviousMs -gt 0) { throw "Turn $($declared.id) cannot declare both gap and overlap." }
        $ssml = ConvertTo-Ssml ([string]$declared.text) ([string]$declared.id)
        $segmentPath = Join-Path $fixtureDir "$($declared.id).wav"
        $voiceIndex = if ($declared.speaker -eq 'A') { 0 } else { 1 }
        $marks = @([SpikeSpeech]::Render($ssml.ssml, $segmentPath, $voices[$voiceIndex]) | ForEach-Object { [ordered]@{ name=$_.Name; seconds=[double]$_.Seconds } })
        if ($marks.Count -ne $ssml.tokens.Count) { throw "SAPI bookmark timing was incomplete for $($declared.id)." }
        $segmentDuration = Get-WavDuration $segmentPath
        $start = if ($turnIndex -eq 0) { 0.0 } elseif ([int]$declared.overlapPreviousMs -gt 0) { $previousEnd - ([int]$declared.overlapPreviousMs / 1000.0) } else { $previousEnd + ([int]$declared.gapAfterPreviousMs / 1000.0) }
        if ($start -lt 0) { throw "Turn $($declared.id) has a negative scheduled start." }
        $end = $start + $segmentDuration
        $effects = @($declared.effects | ForEach-Object { [string]$_ })
        $turn = [ordered]@{ id=[string]$declared.id; index=$turnIndex; speaker=[string]$declared.speaker; voice=$voices[$voiceIndex]; start=[math]::Round($start,6); end=[math]::Round($end,6); duration=[math]::Round($segmentDuration,6); effects=$effects; text=[string]$declared.text; tokenCount=$ssml.tokens.Count; path=$segmentPath }
        $turns += $turn
        if ([int]$declared.overlapPreviousMs -gt 0) {
            $overlapEnd = [math]::Min($previousEnd,$end)
            $overlapIntervals += [ordered]@{ turnId=[string]$declared.id; interruptedTurnId=[string]$turns[$turnIndex-1].id; start=[math]::Round($start,6); end=[math]::Round($overlapEnd,6); duration=[math]::Round($overlapEnd-$start,6) }
        }
        if (Test-Effect $declared 'phone-band') { $phoneIntervals += [ordered]@{ turnId=[string]$declared.id; start=[math]::Round($start,6); end=[math]::Round($end,6); duration=[math]::Round($segmentDuration,6) } }
        for ($wordIndex=0; $wordIndex -lt $marks.Count; $wordIndex++) {
            $uglyBookmarks += [ordered]@{ name=$marks[$wordIndex].Name; word=$ssml.tokens[$wordIndex]; seconds=[math]::Round($start+[double]$marks[$wordIndex].seconds,6); speaker=[string]$declared.speaker; turnId=[string]$declared.id; turnIndex=$turnIndex; tokenIndex=$wordIndex }
        }
        $previousEnd = $end
    }
    $uglyBookmarks = @($uglyBookmarks | Sort-Object @{Expression={ [double]$_.seconds }}, @{Expression={ [int]$_.turnIndex }}, @{Expression={ [int]$_.tokenIndex }})
    for($index=0;$index -lt $uglyBookmarks.Count;$index++){$uglyBookmarks[$index].ordinal=$index}
    $uglyReference = (@($uglyBookmarks | ForEach-Object { $_.word }) -join ' ')
    $maxTurnEnd=0.0;foreach($turn in $turns){if([double]$turn.end -gt $maxTurnEnd){$maxTurnEnd=[double]$turn.end}}
    $uglyMixDuration = [math]::Ceiling($maxTurnEnd + 0.25)
    $ugly = Join-Path $fixtureDir 'ugly-dialogue.wav'

    $mixArguments = @('-y')
    foreach ($turn in $turns) { $mixArguments += @('-i',$turn.path) }
    $mixArguments += @('-f','lavfi','-i',"anoisesrc=color=$($uglyRecipe.disturbances.hvac.color):sample_rate=16000:seed=$($uglyRecipe.disturbances.hvac.seed):duration=$uglyMixDuration")
    $mixArguments += @('-f','lavfi','-i',"sine=frequency=$($uglyRecipe.disturbances.tonalAmbience.frequencyHz):sample_rate=16000:duration=$uglyMixDuration")
    $impulseExpression = "aevalsrc=if(lt(mod(t\,$($uglyRecipe.disturbances.clothingImpulses.periodSeconds))\,$($uglyRecipe.disturbances.clothingImpulses.widthSeconds))\,$($uglyRecipe.disturbances.clothingImpulses.volume)\,0):s=16000:d=$uglyMixDuration"
    $mixArguments += @('-f','lavfi','-i',$impulseExpression)
    $filterParts = @()
    $mixLabels = @()
    for ($index=0; $index -lt $turns.Count; $index++) {
        $turn = $turns[$index]
        $chain = @()
        if (@($turn.effects) -contains 'phone-band') { $chain += "highpass=f=$($uglyRecipe.disturbances.phoneBand.highpassHz)"; $chain += "lowpass=f=$($uglyRecipe.disturbances.phoneBand.lowpassHz)" }
        if (@($turn.effects) -contains 'clipped-peaks') { $chain += "volume=$($uglyRecipe.disturbances.clippedPeaks.pregain)"; $chain += "asoftclip=type=$($uglyRecipe.disturbances.clippedPeaks.type)"; $chain += "volume=$($uglyRecipe.disturbances.clippedPeaks.postgain)" }
        $chain += "adelay=$([math]::Round([double]$turn.start*1000)):all=1"
        $label = "turn$index"
        $filterParts += "[$index`:a]$($chain -join ',')[$label]"
        $mixLabels += "[$label]"
    }
    $hvacIndex = $turns.Count
    $toneIndex = $turns.Count + 1
    $impulseIndex = $turns.Count + 2
    $filterParts += "[$hvacIndex`:a]volume=$($uglyRecipe.disturbances.hvac.volume)[hvac]"
    $filterParts += "[$toneIndex`:a]volume=$($uglyRecipe.disturbances.tonalAmbience.volume)[tone]"
    $filterParts += "[$impulseIndex`:a]anull[impulses]"
    $reverb = $uglyRecipe.disturbances.reverb
    $filterParts += "$($mixLabels -join '')[hvac][tone][impulses]amix=inputs=$($turns.Count+3):duration=longest:normalize=0,aecho=$($reverb.inGain):$($reverb.outGain):$($reverb.delayMs):$($reverb.decay),aresample=16000[out]"
    $complex = $filterParts -join ';'
    $mixArguments += @('-filter_complex',$complex,'-map','[out]','-t',[string]$uglyMixDuration,'-ac','1','-ar','16000','-c:a','pcm_s16le',$ugly)
    $mix = Invoke-External $ffmpeg $mixArguments 600 $script:Scratch 'fixture-ugly'
    if ($mix.exitCode -ne 0 -or $mix.timedOut) { throw "Ugly fixture generation failed: $($mix.stderr)" }
    $uglyDuration = Get-WavDuration $ugly

    $tiny = Join-Path $fixtureDir 'failure-tiny.wav'
    $tinyRun = Invoke-External $ffmpeg @('-y','-f','lavfi','-i','sine=frequency=440:sample_rate=16000:duration=1','-ac','1','-ar','16000','-c:a','pcm_s16le',$tiny) 30 $script:Scratch 'fixture-tiny'
    if ($tinyRun.exitCode -ne 0 -or $tinyRun.timedOut) { throw 'Tiny fixture generation failed.' }

    $fixtures = [ordered]@{
        jfk=[ordered]@{ id='jfk-smoke'; path=$jfk; duration=Get-WavDuration $jfk; sha256=Get-Sha256 $jfk; reference=[string](Get-RecipeFixture $recipe 'jfk-smoke').gold }
        clean=[ordered]@{ id='clean-keyterms'; path=$clean; duration=$cleanDuration; sha256=Get-Sha256 $clean; reference=$cleanText; keyterms=@($cleanRecipe.keyterms | ForEach-Object { [string]$_ }); voice=$voices[0]; tokens=$cleanSsml.tokens; bookmarks=$cleanMarks }
        ugly=[ordered]@{ id='ugly-dialogue'; path=$ugly; duration=$uglyDuration; sha256=Get-Sha256 $ugly; reference=$uglyReference; voices=@($voices[0],$voices[1]); bookmarks=$uglyBookmarks; turns=$turns; overlapIntervals=$overlapIntervals; phoneIntervals=$phoneIntervals; disturbances=$uglyRecipe.disturbances; disturbanceComponents=@('hvac','reverb','clothingImpulses','tonalAmbience','phoneBand','clippedPeaks'); generationFilters=@($mixArguments | Where-Object { $_ -match '^(anoisesrc|sine|aevalsrc)=' }) + @($complex) }
        long=[ordered]@{ id='long-stability'; path=(Join-Path $fixtureDir 'long-stability.wav'); skipped=[bool]$SkipLongFixture; duration=$null; sha256=$null; sentinel=[string]$longRecipe.sentinel; variants=@(); segments=@(); joins=@(); expectedJoinCount=0; bookmarks=@(); reference=''; sentinelPositions=@(); expectedSentinelTimes=@(); expectedSentinelCount=0 }
        tiny=[ordered]@{ id='failure-tiny'; path=$tiny; duration=Get-WavDuration $tiny; sha256=Get-Sha256 $tiny }
    }

    if (-not $SkipLongFixture) {
        $variants = @()
        foreach ($declaredVariant in @($longRecipe.variantCycle)) {
            $sourceFixture = if ([string]$declaredVariant.sourceFixture -eq 'ugly-dialogue') { $fixtures.ugly } elseif ([string]$declaredVariant.sourceFixture -eq 'clean-keyterms') { $fixtures.clean } else { throw "Unknown long variant source fixture: $($declaredVariant.sourceFixture)" }
            $variantPath = Join-Path $fixtureDir "$($declaredVariant.id).wav"
            $variantSamples=[int64][math]::Round([double]$sourceFixture.duration*16000)
            $variantFilter = "$($declaredVariant.filters),aresample=16000,apad=pad_len=$variantSamples,atrim=end_sample=$variantSamples,asetpts=N/SR/TB"
            $variantRun = Invoke-External $ffmpeg @('-y','-i',$sourceFixture.path,'-af',$variantFilter,'-ac','1','-ar','16000','-c:a','pcm_s16le',$variantPath) 300 $script:Scratch "fixture-variant-$($declaredVariant.id)"
            if ($variantRun.exitCode -ne 0 -or $variantRun.timedOut) { throw "Long fixture variant failed: $($declaredVariant.id)" }
            $variantDuration = Get-WavDuration $variantPath
            if ([math]::Abs($variantDuration-[double]$sourceFixture.duration) -gt 0.001) { throw "Long variant $($declaredVariant.id) changed source duration." }
            $variants += [ordered]@{ id=[string]$declaredVariant.id; sourceFixture=[string]$declaredVariant.sourceFixture; filters=$variantFilter; path=$variantPath; duration=$variantDuration; sha256=Get-Sha256 $variantPath; bookmarks=$sourceFixture.bookmarks }
        }
        $segments = @()
        $joins = @()
        $longBookmarks = @()
        $cursor = 0.0
        $segmentIndex = 0
        $targetDuration = [double]$longRecipe.targetDurationSeconds
        while ($cursor -lt $targetDuration - 0.0005) {
            $variant = $variants[$segmentIndex % $variants.Count]
            $usedDuration = [math]::Min([double]$variant.duration,$targetDuration-$cursor)
            if ($segmentIndex -gt 0) { $joins += [ordered]@{ index=$segmentIndex; seconds=[math]::Round($cursor,6); leftVariantId=$segments[$segmentIndex-1].variantId; rightVariantId=$variant.id } }
            $segments += [ordered]@{ index=$segmentIndex; variantId=$variant.id; sourceFixture=$variant.sourceFixture; start=[math]::Round($cursor,6); end=[math]::Round($cursor+$usedDuration,6); sourceStart=0.0; sourceEnd=[math]::Round($usedDuration,6); truncated=($usedDuration -lt [double]$variant.duration-0.0005); sha256=$variant.sha256 }
            foreach ($bookmark in @($variant.bookmarks)) {
                if ([double]$bookmark.seconds -lt $usedDuration) {
                    $longBookmarks += [ordered]@{ name=[string]$bookmark.name; word=[string]$bookmark.word; seconds=[math]::Round($cursor+[double]$bookmark.seconds,6); sourceOrdinal=$(if($bookmark.Contains('ordinal')){[int]$bookmark.ordinal}else{0}); segmentIndex=$segmentIndex; variantId=$variant.id; sourceFixture=$variant.sourceFixture }
                }
            }
            $cursor += $usedDuration
            $segmentIndex++
        }
        $concatPath = Join-Path $fixtureDir 'long-concat.txt'
        $concatLines = @()
        foreach ($segment in $segments) {
            $segmentVariant = @($variants | Where-Object { $_.id -eq $segment.variantId })[0]
            $concatLines += "file '$($segmentVariant.path.Replace("'","'\''"))'"
        }
        Write-Utf8Text $concatPath (($concatLines -join "`n") + "`n")
        $longRun = Invoke-External $ffmpeg @('-y','-f','concat','-safe','0','-i',$concatPath,'-t',[string]$targetDuration,'-ac','1','-ar','16000','-c:a','pcm_s16le',$fixtures.long.path) 1200 $script:Scratch 'fixture-long'
        if ($longRun.exitCode -ne 0 -or $longRun.timedOut) { throw "Long fixture generation failed: $($longRun.stderr)" }
        $longBookmarks = @($longBookmarks | Sort-Object @{Expression={ [double]$_.seconds }}, @{Expression={ [int]$_.segmentIndex }}, @{Expression={ [int]$_.sourceOrdinal }})
        foreach ($join in $joins) {
            $allBefore=@(for($index=0;$index -lt $longBookmarks.Count;$index++){if([double]$longBookmarks[$index].seconds -lt [double]$join.seconds){$index}})
            $allAfter=@(for($index=0;$index -lt $longBookmarks.Count;$index++){if([double]$longBookmarks[$index].seconds -ge [double]$join.seconds){$index}})
            $before=@($allBefore | Select-Object -Last 2)
            $after=@($allAfter | Select-Object -First 2)
            $join.referenceIndexes=@($before+$after)
            $join.expectedWords=@($join.referenceIndexes | ForEach-Object { [string]$longBookmarks[[int]$_].word })
        }
        $sentinelWords = @((Normalize-Transcript ([string]$longRecipe.sentinel)) -split ' ' | Where-Object { $_ })
        if ($sentinelWords.Count -ne 2) { throw 'The long fixture sentinel must contain exactly two normalized words.' }
        $sentinelPositions = @(Get-SentinelPositions $longBookmarks $sentinelWords[0] $sentinelWords[1])
        $fixtures.long.skipped=$false
        $fixtures.long.duration=Get-WavDuration $fixtures.long.path
        $fixtures.long.sha256=Get-Sha256 $fixtures.long.path
        $fixtures.long.variants=$variants
        $fixtures.long.segments=$segments
        $fixtures.long.joins=$joins
        $fixtures.long.expectedJoinCount=$joins.Count
        $fixtures.long.bookmarks=$longBookmarks
        $fixtures.long.reference=(@($longBookmarks | ForEach-Object { $_.word }) -join ' ')
        $fixtures.long.sentinelPositions=$sentinelPositions
        $fixtures.long.expectedSentinelTimes=@($sentinelPositions | ForEach-Object { $_.seconds })
        $fixtures.long.expectedSentinelCount=$sentinelPositions.Count
    }

    $validation = Test-RepresentativeFixtures $fixtures $recipe ([bool]$SkipLongFixture)
    $persisted = $fixtures | ConvertTo-Json -Depth 40 | ConvertFrom-Json
    foreach ($property in $persisted.psobject.Properties) {
        if ($property.Value.path) { $property.Value.path = '<SCRATCH>\fixtures\' + [IO.Path]::GetFileName([string]$property.Value.path) }
    }
    foreach ($variant in @($persisted.long.variants)) { $variant.path = '<SCRATCH>\fixtures\' + [IO.Path]::GetFileName([string]$variant.path) }
    foreach ($turn in @($persisted.ugly.turns)) { $turn.psobject.Properties.Remove('path') }
    $manifest = [ordered]@{ schemaVersion=2; generatedUtc=[DateTime]::UtcNow.ToString('o'); recipeSha256=Get-Sha256 $recipePath; validation=$validation; fixtures=$persisted }
    Write-Json (Join-Path $script:RawRoot 'fixture-manifest.json') $manifest 50
    $script:FixtureState = $fixtures
    return $fixtures
}
